# =====================================================
# Data displayed on the Home (About Me) page.
#
# üí° Tip for Images / Logo:
# You can use either:
# 1. A full URL (e.g., https://example.com/logo.png)
# 2. A local file placed under /public/images/ and referenced with "/" (e.g., "/images/logo.png")
# =====================================================

# =====================================================
# üë§ Personal Information
# =====================================================

profile:
  name: "Harsh Rajesh Shah"
  headline: "Student @ University of Southern California"
  email: "hrshah@usc.edu"
  location: "Los Angeles , California"
  profileImage: "https://github.com/pm25.png"

  links:
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/harsh-shah16"
      icon:
        name: "FaLinkedin"
        package: "react-icons/fa6"

    # - name: "Google Scholar"
    #   url: "https://scholar.google.com/citations?user=[your-id]"
    #   icon:
    #     name: "FaGoogleScholar"
    #     package: "react-icons/fa6"

    - name: "R√©sum√©"
      url: "/pdf/resume.pdf"
      icon:
        name: "FaRegIdBadge"
        package: "react-icons/fa6"

    - name: "Github"
      url: "https://github.com/harshshah1618"
      icon:
        name: "FaGithub"
        package: "react-icons/fa6"


  # you can use HTML syntax here (e.g. <br/>, <a>, <strong>, ...)
  biography: |
   biography: |
    Hi! I'm <strong>Harsh</strong>, a <em>Computer Science Graduate Student</em> passionate about <em>scalable systems, quantum computing, and the broader world of AI</em>. Currently, I am pursuing my Master's degree at the <em>University of Southern California</em>, where I am expanding my technical expertise. 
    With a background as a <em>Full-Stack Engineer</em>, I am eager to apply my skills to solving complex problems.
    <div class="my-2"></div>
    I would love to meet with like-minded people in the field. I‚Äôm also looking for <b>Summer 2026 internship opportunities</b>. Thanks for visiting! Feel free to <a href="mailto:[your-email@example.com]" target="_blank" rel="noopener noreferrer">reach out</a> to connect or if you know of any relevant openings.

# # =====================================================
# # üéì Education Section
# # =====================================================

education:

  - degree: "M.S. in Computer Science"
    school: "University of Southern California"
    years: "2025 - present"
    logo: "/images/usc.png"

  - degree: "B.E. in Computer Science"
    school: "JSS Science and Technology University"
    years: "2019 - 2023"
    logo: "/images/jss.jpg"

# # =====================================================
# # üíº Work Experience Section
# # =====================================================

workExperience:
  - title: "Software Engineer"
    company: "Fidelity Investments"
    years: "Aug 2023 - Aug 2025"
    logo: "/images/fidelity.jpg"

  - title: "Software Engineering Intern"
    company: "Fidelity Investments"
    years: "Feb 2023 - June 2023"
    logo: "/images/fidelity.jpg"

  - title: "Research Intern"
    company: "GE Healthcare"
    years: "Aug 2022- Nov 2022"
    logo: "/images/ge.jpg"

# # =====================================================
# # üé§ Presentations / Talks Section
# # =====================================================

talks:
  - category: "Misc"
    title: "[Your Talk Title Here]"
    organization: "[Your Talk Location Here]"
    date: "[Month Day, Year]"
    link: "https://example.com/your-talk-link"
    image: "https://upload.wikimedia.org/wikipedia/commons/8/8f/Example_image.svg"

  - category: "Workshop"
    title: "Deep Learning with Keras"
    organization: "University of Illinois Urbana-Champaign (UIUC)"
    date: "Sep 4, 2019"
    link: null
    image: "https://pm25.github.io/images/uiuc-workshop.webp"

  - category: "Workshop"
    title: "Practical Guide to PyTorch"
    organization: "ABC University"
    date: "Dec 5, 2022"
    link: "https://example.com/workshop-talk"
    image: null

# # =====================================================
# # üõ°Ô∏è Professional Services
# # =====================================================

services:
  - category: "Misc"
    role: "[Role]"
    organization: "[Organization]"
    date: "[Year]"
    link: "https://example.com/workshop-talk"
    image: "https://upload.wikimedia.org/wikipedia/commons/8/8f/Example_image.svg"

  - category: "Research"
    role: "Reviewer"
    organization: "TPAMI 2024, NeurIPS 2025"
    date: "2024-2025"
    link: null
    image: null

  - category: "Research"
    role: "Program Committee Member"
    organization: "CVPR 2022"
    date: "2022"
    link: null
    image: null

  - category: "Teaching"
    role: "Teaching Assistant"
    organization: "National Taiwan University - Data Structures & Algorithms"
    date: "2021"
    link: null
    image: null

# # =====================================================
# # üõ†Ô∏è Skills Section
# # =====================================================

skills:
  Programming:
    - name: "[Name]"
      logo: "https://upload.wikimedia.org/wikipedia/commons/1/18/ISO_C%2B%2B_Logo.svg"
      proficiency: "[Proficiency]"
      description: "[Description]"

    - name: "Python"
      logo: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg"
      proficiency: Experienced
      description: null

    - name: "JavaScript"
      logo: "https://upload.wikimedia.org/wikipedia/commons/9/99/Unofficial_JavaScript_logo_2.svg"
      proficiency: Fluent
      description: null

  Web:
    - name: "React"
      logo: "https://upload.wikimedia.org/wikipedia/commons/3/30/React_Logo_SVG.svg"
      proficiency: Advanced
      description: null

    - name: "Typescript"
      logo: "https://upload.wikimedia.org/wikipedia/commons/f/f5/Typescript.svg"
      proficiency: Fluent
      description: null

    - name: "TailwindCSS"
      logo: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Tailwind_CSS_Logo.svg"
      proficiency: Fluent
      description: null

    - name: "Next.js"
      logo: "https://logo.svgcdn.com/devicon/nextjs-original.png"
      proficiency: Fluent
      description: null

  Machine Learning:
    - name: "PyTorch"
      logo: "https://upload.wikimedia.org/wikipedia/commons/1/10/PyTorch_logo_icon.svg"
      proficiency: Experienced
      description: null

    - name: "TensorFlow"
      logo: "https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg"
      proficiency: Fluent
      description: null

    - name: "Keras"
      logo: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Keras_logo.svg"
      proficiency: Fluent
      description: null

  Research:
    - name: "Machine Learning"
      logo: "https://upload.wikimedia.org/wikipedia/commons/2/2a/OOjs_UI_icon_academic-progressive.svg"
      proficiency: 2020 - Current
      description: "General machine learning methods and applied research."

    - name: "Representation Learning"
      logo: "https://upload.wikimedia.org/wikipedia/commons/2/2a/OOjs_UI_icon_academic-progressive.svg"
      proficiency: 2024 - 2025
      description: "Learning meaningful embeddings and feature representations from data."

  Language:
    - name: "English"
      logo: "https://upload.wikimedia.org/wikipedia/commons/e/e0/OOjs_UI_icon_language-ltr-progressive.svg"
      proficiency: Fluent
      description: "Professional working proficiency."

    - name: "Taiwanese Hokkien"
      logo: "https://upload.wikimedia.org/wikipedia/commons/e/e0/OOjs_UI_icon_language-ltr-progressive.svg"
      proficiency: Native
      description: "Native fluency."
