# =====================================================
# Website Configuration
# This section contains general information about your website.
# =====================================================

site:
  name: "harsh's site"
  repoUrl: "https://github.com/pm25/showlit"
  description: "Personal and professional portfolio of me!"
  author: "Harsh Shah"
